name: Bug Report
description: Use this template for reporting a bug.
labels: ["Type: Bug"]
assignees:
  - Levminer
body:
- type: checkboxes
  attributes:
    label: Before the bug report.
    description: Please ensure you've completed all of the following.
    options:
      - label: I have searched the [Github Issues](https://www.github.com/levminer/authme/issues) for a bug that matches the one I want to file, without success.
        required: true
- type: textarea
  attributes:
    label: Authme/System information
    description: Paste the version information here (Settings > About > About Authme > Copy).
    placeholder: "Authme: 2.6.0 ..."
  validations:
    required: true
- type: textarea
  attributes:
    label: Authme log
    description: Paste the latest log here (Settings > About > Logs > Show logs).
    placeholder: "[AUTHME LOG] {2023. 07. 31. 10:00:00} Authme 3.0.0 release.220713.092658  ..."
- type: textarea
  attributes:
    label: Describe the bug
    description: A clear and concise description of what the bug is.
  validations:
    required: true
- type: textarea
  attributes:
    label: To reproduce
    description: Steps to reproduce the behavior.
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional information
    description: If your problem needs further explanation, please add more information here.
